//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Runtime Version: 4.0.30319.34014
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

{$HIDE H7}
{$HIDE W1}
{$HIDE W27}
{$HIDE H11}

namespace SampleServer;

interface

uses
  System,
  RemObjects.SDK,
  RemObjects.SDK.Types,
  RemObjects.SDK.Server,
  RemObjects.SDK.Server.ClassFactories;
  
type
  [RemObjects.SDK.Server.ClassFactories.StandardClassFactory]
  [RemObjects.SDK.Server.Service(Name := 'BusinessLogicService', InvokerClass := typeOf(BusinessLogicService_Invoker), ActivatorClass := typeOf(BusinessLogicService_Activator))]
  BusinessLogicService = public class(RemObjects.SDK.Server.Service, IBusinessLogicService)
  private 
    method InitializeComponent;
    var components: System.ComponentModel.Container := nil;
  protected 
    method Dispose(aDisposing: System.Boolean); override;
  public 
    constructor;
    method Process(Value: System.String): System.Int32; virtual;
    method &Reverse(Value: String): String; virtual;
  end;
  
implementation

{ BusinessLogicService }

constructor BusinessLogicService;
begin
  inherited constructor();
  self.InitializeComponent();
end;

method BusinessLogicService.InitializeComponent;
begin
end;

method BusinessLogicService.Dispose(aDisposing: System.Boolean);
begin
  if aDisposing then begin
    if (self.components <> nil) then begin
      self.components.Dispose();
    end;
  end;
  inherited Dispose(aDisposing);
end;

method BusinessLogicService.Process(Value: System.String): System.Int32;
begin
  result := (new BusinessLogic.StringProcessor).Process(Value);
end;

method BusinessLogicService.Reverse(Value: String): String;
begin
  result := (new BusinessLogic.StringProcessor).&Reverse(Value);
end;

end.
